from tkinter import *

win = Tk()
win.title("Memorizer :)")

memories = []

def add():
    memories.append(str(input_box.get()))
    
def remove():
    try:
        memories.remove(str(input_box.get()))
        
    except:
        print("No GOBLIN ROWAOOAOWROAOOAWOROAWOOROAWOROAWOROAWOROAWROOROAWOROWAWOROAOWROOROAWROAWOROAWOROAWROAOWROWAORROWAOOAOWROAOOAWOROAWOOROAWOROAWOROAWOROAWROOROAWOROWAWOROAOWROOROAWROAWOROAWOROAWROAOWROWAORROWAOOAOWROAOOAWOROAWOOROAWOROAWOROAWOROAWROOROAWOROWAWOROAOWROOROAWROAWOROAWOROAWROAOWROWAORROWAOOAOWROAOOAWOROAWOOROAWOROAWOROAWOROAWROOROAWOROWAWOROAOWROOROAWROAWOROAWOROAWROAOWROWAORROWAOOAOWROAOOAWOROAWOOROAWOROAWOROAWOROAWROOROAWOROWAWOROAOWROOROAWROAWOROAWOROAWROAOWROWAORROWAOOAOWROAOOAWOROAWOOROAWOROAWOROAWOROAWROOROAWOROWAWOROAOWROOROAWROAWOROAWOROAWROAOWROWAORROWAOOAOWROAOOAWOROAWOOROAWOROAWOROAWOROAWROOROAWOROWAWOROAOWROOROAWROAWOROAWOROAWROAOWROWAORROWAOOAOWROAOOAWOROAWOOROAWOROAWOROAWOROAWROOROAWOROWAWOROAOWROOROAWROAWOROAWOROAWROAOWROWAORROWAOOAOWROAOOAWOROAWOOROAWOROAWOROAWOROAWROOROAWOROWAWOROAOWROOROAWROAWOROAWOROAWROAOWROWAORROWAOOAOWROAOOAWOROAWOOROAWOROAWOROAWOROAWROOROAWOROWAWOROAOWROOROAWROAWOROAWOROAWROAOWROWAORROWAOOAOWROAOOAWOROAWOOROAWOROAWOROAWOROAWROOROAWOROWAWOROAOWROOROAWROAWOROAWOROAWROAOWROWAORROWAOOAOWROAOOAWOROAWOOROAWOROAWOROAWOROAWROOROAWOROWAWOROAOWROOROAWROAWOROAWOROAWROAOWROWAORROWAOOAOWROAOOAWOROAWOOROAWOROAWOROAWOROAWROOROAWOROWAWOROAOWROOROAWROAWOROAWOROAWROAOWROWAORROWAOOAOWROAOOAWOROAWOOROAWOROAWOROAWOROAWROOROAWOROWAWOROAOWROOROAWROAWOROAWOROAWROAOWROWAORROWAOOAOWROAOOAWOROAWOOROAWOROAWOROAWOROAWROOROAWOROWAWOROAOWROOROAWROAWOROAWOROAWROAOWROWAORROWAOOAOWROAOOAWOROAWOOROAWOROAWOROAWOROAWROOROAWOROWAWOROAOWROOROAWROAWOROAWOROAWROAOWROWAOR")
    
def show():
    print(memories)

show_button = Button(win, text="Reveal", command=show)
show_button.grid(rows=3, column=5)

title = Label(win, text="Memorisor")
title.grid(rows=1, columns=5, columnspan=1)

add_button = Button(win, text="ADD", command=add)
add_button.grid(rows=2, columns=5, columnspan=1)

remove_button = Button(win, text="Deport", command=remove)
remove_button.grid(rows=7, columns=5, columnspan=1)

input_box = Entry(win, width=20)
input_box.grid(rows=3, columns=5, columnspan=1)





win.mainloop()

